In [1]:
%matplotlib inline
import numpy as np, scipy as sp, matplotlib.pyplot as plt

In [2]:
#Transpose
#Transposing a dataset means swapping its rows and columns so that the rows become columns and the columns become rows
#For many chart types in Datawrapper, transposing a table means that the x-axis and y-axis swap 
#Often, when your chart looks funny, all you need to do is to transpose the data 
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


In [3]:
#Multiplication of matrices and vector
#Note that we used the reshape() function to reshape the vector into a 2 by 1 matrix (the -1 tells Numpy to guess the remaining number). 
#Without it, you would end with a one-dimensional array instead of a two-dimensional array here (a matrix with a single column)
A = np.array([
    [1, 2],
    [5, 6],
    [7, 8]
])
v = np.array([3, 4]).reshape(-1, 1)
A @ v

array([[11],
       [39],
       [53]])

In [15]:
#Covariance Matrix
#The dot product of a matrix with its transpose corresponds to the covariance matrix
#Covariance measures how much two random variables vary together in a population
#When the population contains higher dimensions or more random variables, a matrix is used to describe the relationship between different dimensions
x = np.random.normal(10, 2, 100)
y = x * 1.5 + np.random.normal(25, 5, 100)
z = x * 2 + np.random.normal(0, 1, 100)

In [16]:
np.cov([x, y, z])

array([[ 3.85849444,  5.47036789,  7.87758583],
       [ 5.47036789, 25.24911365, 11.0764449 ],
       [ 7.87758583, 11.0764449 , 16.82050492]])

In [17]:
X = np.vstack([x, y, z]).T
X.shape

(100, 3)

In [18]:
X = X - X.mean(axis=0)

In [19]:
(X.T @ X) / (X.shape[0] - 1)

array([[ 3.85849444,  5.47036789,  7.87758583],
       [ 5.47036789, 25.24911365, 11.0764449 ],
       [ 7.87758583, 11.0764449 , 16.82050492]])